// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmcsbmbyglzkefbjqdnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtY3NibWJ5Z2x6a2VmYmpxZG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk4Nzc3NDQsImV4cCI6MjA1NTQ1Mzc0NH0.sRoZiqOncSQ07PudIQiFGh5JwCowOYMazh6ihXOk7-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);